freeze("$(PORT_DIR)/modules")
include("$(MPY_DIR)/extmod/uasyncio")

# Useful networking-related packages.
require("bundle-networking")

# Require some micropython-lib modules.
# require("aioespnow")
#require("dht")
#require("ds18x20")
require("neopixel")
#require("onewire")
#require("umqtt.robust")
#require("umqtt.simple")
#require("upysh")

module("wifimanager.py")
module("battery.py")
module("config.py")
module("led.py")
module("minilog.py")
module("modes.py")
module("organtuner.py")
module("pinout.py")
module("player.py")
module("setlist.py")
module("soleble.py")
module("solenoid.py")
module("tachometer.py")
module("tunelist.py")
module("webserver.py")

module("vfsfrozen.py")
module("frozen_lib.py")
module("frozen_root.py")
module("frozen_src.py")
module("frozen_static.py")
module("frozen_tunelib.py")
module("frozenfiles.py")

module("aioblemidi.py", base_path = "../../midi-ble/aioblemidi" )
module("mcp23017.py")
package("tinyweb")
module("umidiparser.py", base_path="../../umidiparser/src_v1.3/umidiparser")
